---
- name: Configure sudo to not prompt for password for wheel group
  lineinfile:
    dest: /etc/sudoers
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: Create cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Add user accounts
  user:
    name: "{{ item }}"
    groups: cloudadmins,wheel
    password: "$y$clAKLC@@@1$q1mlEHBiWgT??"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "{{ user_ssh_key_file }}"
  loop:
    - user1000
    - user2000

- name: Add authorized keys for users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', user_ssh_key_file + '.pub') }}"
  loop:
    - user1000
    - user2000
